---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  namespace: traefik
spec:
  dnsNames:
    - 'jellyfin.cluster.domain'
  secretName: jellyfin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls
  namespace: traefik
spec:
  dnsNames:
    - 'whoami.cluster.domain'
  secretName: whoami-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer    