apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs
  namespace: nfs
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-server-provisioner
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: nfs
        namespace: flux-system
      interval: 1m
  values:
    persistence:
      enabled: true
      storageClass: "default"
      size: 100Gi
    storageClass:
      defaultClass: true