---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager-conf
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: certmanager
  path: ./infra/cert-manager/conf
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system