apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
  interval: 10m